<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0;net8.0</TargetFrameworks>
		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>sixnet.snk</AssemblyOriginatorKeyFile>
		<Authors>DingBin.Li</Authors>
		<Copyright>Copyright © DingBin.Li</Copyright>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Sixnet" Version="2.1.1" />
		<PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
	</ItemGroup>

</Project>
